name: Trigger auto deployment for container-app-x2ur4eg25zhkq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-x2ur4eg25zhkq-AutoDeployTrigger-bd8c9f62-e86c-4f01-913a-fdd6f43365bf.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPX2UR4EG25ZHKQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPX2UR4EG25ZHKQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPX2UR4EG25ZHKQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPX2UR4EG25ZHKQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPX2UR4EG25ZHKQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-x2ur4eg25zhkq
          resourceGroup: todonodejspgsqlgoogleauth97218fae
          imageToBuild: default/container-app-x2ur4eg25zhkq:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


